In [3]:
import numpy as np
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(notre_tableau)
type(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


numpy.ndarray

In [4]:
mon_array_bidimensionnel=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mon_array_bidimensionnel)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(mon_array_bidimensionnel[0][2])
print(mon_array_bidimensionnel[0, 2])

# Pour selectionner la premiére ligne
print(mon_array_bidimensionnel[:,0])

# Pour selectionner le premiére colonne
print(mon_array_bidimensionnel[0,:])

3
3
[1 4 7]
[1 2 3]


In [6]:
mon_array_bidimensionnel[0,0]="texte"

ValueError: invalid literal for int() with base 10: 'texte'

In [80]:
mon_array_bidimensionnel.dtype

dtype('int64')

In [81]:
mon_array_bidimensionnel=np.array([[1.5,2,3],[4,5.2,6],[7,8,9.1]], dtype = float)
print(mon_array_bidimensionnel)
mon_array_bidimensionnel.dtype

[[1.5 2.  3. ]
 [4.  5.2 6. ]
 [7.  8.  9.1]]


dtype('float64')

In [82]:
import numpy as np
# np.zeros() permet de créer des un ndarray don't l'ensemble des éléments correspondent à la valeur 0
mon_array_zeros = np.zeros((4,6))
print(mon_array_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [83]:
import numpy as np
# Si on veut on peut spécifier le type du tableau
mon_array_zeros = np.zeros((4,6), dtype = int)
print(mon_array_zeros)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [84]:
import numpy as np
# Si on veut on peut spécifier le type du tableau
mon_array_ones = np.ones((4,6), dtype = int)
print(mon_array_ones)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [85]:
import numpy as np
# np.random/random() permet de créer un tableau avec des éléments aléatoire
mon_array_random = np.random.random((4,2))
print(mon_array_random)

[[0.98291917 0.66919991]
 [0.32810662 0.99766006]
 [0.96686372 0.93170518]
 [0.82547912 0.0220214 ]]


In [86]:
#
import numpy as np

iris = np.genfromtxt("fichiers_CSV/iris.csv", delimiter = ";", skip_header = True, encoding='latin-1')
print(iris)
print(iris.dtype)
type(iris)

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

numpy.ndarray

In [87]:
import numpy as np
np.savetxt("fichiers_CSV/iris2.csv", iris, delimiter = ";")

In [88]:
iris[2,1]

3.2

In [89]:
iris[2,1] = 4
iris[2,1]

4.0

In [90]:
iris[2,1] = 3.2
iris[2,1]

3.2

In [91]:
iris[iris>2]

array([5.1, 3.5, 4.9, 3. , 4.7, 3.2, 4.6, 3.1, 5. , 3.6, 5.4, 3.9, 4.6,
       3.4, 5. , 3.4, 4.4, 2.9, 4.9, 3.1, 5.4, 3.7, 4.8, 3.4, 4.8, 3. ,
       4.3, 3. , 5.8, 4. , 5.7, 4.4, 5.4, 3.9, 5.1, 3.5, 5.7, 3.8, 5.1,
       3.8, 5.4, 3.4, 5.1, 3.7, 4.6, 3.6, 5.1, 3.3, 4.8, 3.4, 5. , 3. ,
       5. , 3.4, 5.2, 3.5, 5.2, 3.4, 4.7, 3.2, 4.8, 3.1, 5.4, 3.4, 5.2,
       4.1, 5.5, 4.2, 4.9, 3.1, 5. , 3.2, 5.5, 3.5, 4.9, 3.6, 4.4, 3. ,
       5.1, 3.4, 5. , 3.5, 4.5, 2.3, 4.4, 3.2, 5. , 3.5, 5.1, 3.8, 4.8,
       3. , 5.1, 3.8, 4.6, 3.2, 5.3, 3.7, 5. , 3.3, 7. , 3.2, 4.7, 6.4,
       3.2, 4.5, 6.9, 3.1, 4.9, 5.5, 2.3, 4. , 6.5, 2.8, 4.6, 5.7, 2.8,
       4.5, 6.3, 3.3, 4.7, 4.9, 2.4, 3.3, 6.6, 2.9, 4.6, 5.2, 2.7, 3.9,
       5. , 3.5, 5.9, 3. , 4.2, 6. , 2.2, 4. , 6.1, 2.9, 4.7, 5.6, 2.9,
       3.6, 6.7, 3.1, 4.4, 5.6, 3. , 4.5, 5.8, 2.7, 4.1, 6.2, 2.2, 4.5,
       5.6, 2.5, 3.9, 5.9, 3.2, 4.8, 6.1, 2.8, 4. , 6.3, 2.5, 4.9, 6.1,
       2.8, 4.7, 6.4, 2.9, 4.3, 6.6, 3. , 4.4, 6.8, 2.8, 4.8, 6.

In [92]:
# pour récupérer le tuple des dimensions du tableau
iris[iris>2].shape

(472,)

In [93]:
# pour récupérer la première valeur du tuple des dimensions du tableau
iris[iris>2].shape[0]

472

In [94]:
iris > 2

array([[ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, Fal

In [95]:
#pour conserver uniquement les lignes ou les elements de la première colonne du tableau sont supérieur à 5
iris[iris[:,0] > 5]

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4.2, 1.4, 0.2, 1. ],
       [5.5, 3.5, 1.3, 0.2, 1. ],
       [5.1, 3.4, 1.5, 0.2, 1. ],
       [5.1, 3.8, 1.9, 0.4, 1. ],
       [5.1, 3.8, 1.6, 0.2, 1. ],
       [5.3, 3.7, 1.5, 0.2, 1. ],
       [7. , 3.2, 4.7, 1.4, 2. ],
       [6.4, 3.2, 4.5, 1.5, 2. ],
       [6.9, 3.1, 4.9, 1.5, 2. ],
       [5.5, 2.3, 4. , 1.3, 2. ],
       [6.5, 2.8, 4.6, 1.5, 2. ],
       [5.7, 2.8, 4.5, 1.3, 2. ],
       [6.3, 3.3, 4.7, 1.6, 2. ],
       [6.6, 2

In [96]:
#pour conserver uniquement les lignes ou les elements de la deuxieme colonne du tableau sont supérieur à 3
iris[iris[:,1] > 3]

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.6, 0.2, 1. ],
       [4.8, 3.1, 1.6, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4.2, 1.4, 0.2, 1. ],
       [4.9, 3

In [97]:
iris[:,0] > 5

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True, False, False, False,
        True,  True, False, False,  True,  True,  True, False, False,
        True, False, False,  True, False, False, False, False,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [98]:
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Contenu de notre tableau :")
print(notre_tableau)
print("Nouveau tableau après fancy indexing :")
indices = np.array([[4,10,5]])
print(notre_tableau[indices])

Contenu de notre tableau :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Nouveau tableau après fancy indexing :
[[ 5 11  6]]


In [99]:
A = notre_tableau[indices]
print(A[0,2])

6


In [100]:
# pour récupérer les 3 premiers élément avec le slicing
notre_tableau[:3]

array([1, 2, 3])

In [101]:
# les derniers éléments
notre_tableau[10:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [102]:
# du troisième au septième élément
notre_tableau[3:7]

array([4, 5, 6, 7])

In [103]:
# tout les élements avec un pas de 2
notre_tableau[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [104]:
# tout les éléments entre 2 et 8 avec un pas de deux
notre_tableau[2:8:2]

array([3, 5, 7])

In [105]:
# ici on selectionne les deux lignes des 4 premières colonnes (slicing en 2 dimensions)
iris[:2,:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [106]:
# les dernières lignes à partir de l'index 145 des dernières colonnes à partir de l'index 2
iris[:145,:2]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.6],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

In [107]:
# Affiche toutes les colonnes de la ligne 0, la première ligne
iris[0,:]

array([5.1, 3.5, 1.4, 0.2, 1. ])

In [108]:
iris[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [109]:
# Affiche toutes les colonnes de la dernière ligne
iris[-1:]

array([[5.9, 3. , 5.1, 1.8, 3. ]])

In [110]:
#notion de VUE et de COPIE
sous_tableau = notre_tableau[:5]
sous_tableau

array([1, 2, 3, 4, 5])

In [111]:
sous_tableau[0]=10
sous_tableau

array([10,  2,  3,  4,  5])

In [112]:
notre_tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [113]:
# pour créer une copie la méthode est .copy()
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
sous_tableau=notre_tableau[:5].copy()
sous_tableau[0]=10
print(sous_tableau)
print(notre_tableau)

[10  2  3  4  5]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [114]:
# les opérations mathématiques avec NumPy

mon_tableau=np.array([[10,11,12],[13,14,15],[16,17,18]])
mon_tableau

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [115]:
import numpy as np
np.add(mon_tableau,10)

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [116]:
import numpy as np
A = np.multiply(mon_tableau,20)
print(A)
print(mon_tableau)

[[200 220 240]
 [260 280 300]
 [320 340 360]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [117]:
mon_tableau2=np.array([10,20,30])
mon_tableau2
mon_tableau

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [118]:
import numpy as np
np.subtract(mon_tableau,mon_tableau2)

array([[  0,  -9, -18],
       [  3,  -6, -15],
       [  6,  -3, -12]])

In [119]:
mon_tableau3=np.array([[1,2,3],[4,5,6],[7,8,9]])
mon_tableau3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
np.multiply(mon_tableau,mon_tableau3)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [121]:
# Les fonctions d'agrégation

import numpy as np
print("Somme sur l'ensemble des éléments :")
print(np.sum(iris))

# axis = 0 signifie qu'on veut effectuer le calcul par colonne
# et axis = 1 signifie qu'on veut effectué le calcul par ligne

print("Somme par colonne :")
print(np.sum(iris, axis=0))
print("Somme par ligne :")
print(np.sum(iris, axis=1))

Somme sur l'ensemble des éléments :
2378.7
Somme par colonne :
[876.5 458.6 563.7 179.9 300. ]
Somme par ligne :
[11.2 10.5 10.4 10.4 11.2 12.4 10.7 11.1  9.9 10.6 11.8 11.  10.3  9.5
 12.2 13.  12.  11.3 12.5 11.7 11.7 11.7 10.4 11.6 11.3 10.8 11.4 11.4
 11.2 10.7 10.7 11.7 11.9 12.3 10.7 10.6 11.5 11.   9.9 11.2 11.1  9.4
 10.1 11.7 12.2 10.5 11.7 10.4 11.7 10.9 18.3 17.6 18.4 15.1 17.4 16.3
 17.9 13.6 17.4 15.2 13.5 16.6 15.2 17.1 15.4 17.6 16.6 15.6 16.4 15.1
 17.7 16.2 17.2 16.8 16.9 17.4 17.8 18.4 16.9 14.8 14.8 14.6 15.6 17.4
 16.4 17.5 18.  16.3 16.  15.3 15.7 17.1 15.6 13.6 15.8 16.1 16.1 16.7
 13.7 15.9 21.1 18.5 21.1 19.6 20.5 22.3 16.6 21.3 19.8 22.4 19.8 19.3
 20.4 18.2 19.1 20.2 19.8 23.4 22.5 17.7 21.1 18.3 22.2 18.7 20.8 21.2
 18.6 18.8 19.9 20.6 21.2 23.1 20.  18.7 18.7 22.1 20.7 19.8 18.6 20.5
 20.8 20.4 18.5 21.2 21.2 20.2 18.7 19.7 20.3 18.8]


In [122]:
# calcul de la moyenne et de la variance .mean() et .std()
import numpy as np
print(np.mean(iris, axis=0))
print(np.std(iris, axis=0))

[5.84333333 3.05733333 3.758      1.19933333 2.        ]
[0.82530129 0.43441097 1.75940407 0.75969263 0.81649658]


In [123]:
import numpy as np
print(np.max(iris, axis=0))

[7.9 4.4 6.9 2.5 3. ]


In [124]:
iris_1 = iris[iris[:,4] == 1]
iris_2 = iris[iris[:,4] == 2]
iris_3 = iris[iris[:,4] == 3]
# print de la moyenne des 3 iris
print(np.mean(iris_1, axis=0))
print(np.mean(iris_2, axis=0))
print(np.mean(iris_3, axis=0))

[5.006 3.428 1.462 0.246 1.   ]
[5.936 2.77  4.26  1.326 2.   ]
[6.588 2.974 5.552 2.026 3.   ]


In [125]:
# différentes méthodes, .size pour la taille, .shape pour les dimensions,
# ndim = nombre de dimensions ??, .dtype pour savoir le type (int/float)
print("Attribut size:")
print(iris.size)
print("Attribut shape:")
print(iris.shape)
print("Attribut ndim:")
print(iris.ndim)
print("Attribut dtype:")
print(iris.dtype)

Attribut size:
750
Attribut shape:
(150, 5)
Attribut ndim:
2
Attribut dtype:
float64


In [126]:
#méthode pour transposer (inverser lignes et colonnes)
iris.T

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

In [127]:
np.append(notre_tableau,[21,22,23,24,25])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [128]:
np.append(iris,[[10,10,10,10,10]],axis = 0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,  0.2,  1. ],
       [ 5. ,  3. ,  1.6,

In [129]:
import numpy as np
np.insert(notre_tableau, 1, 42)

array([ 1, 42,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [130]:
import numpy as np
np.insert(notre_tableau, 1, [42,43,44,45,46])

array([ 1, 42, 43, 44, 45, 46,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20])

In [131]:
import numpy as np 
np.insert(iris, 1, [10,10,10,10,10], axis = 0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [10. , 10. , 10. , 10. , 10. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,

In [132]:
#on supprime la colonne 2 (à l'index 1)
np.delete(iris, 1, axis = 1)

array([[5.1, 1.4, 0.2, 1. ],
       [4.9, 1.4, 0.2, 1. ],
       [4.7, 1.3, 0.2, 1. ],
       [4.6, 1.5, 0.2, 1. ],
       [5. , 1.4, 0.2, 1. ],
       [5.4, 1.7, 0.4, 1. ],
       [4.6, 1.4, 0.3, 1. ],
       [5. , 1.5, 0.2, 1. ],
       [4.4, 1.4, 0.2, 1. ],
       [4.9, 1.5, 0.1, 1. ],
       [5.4, 1.5, 0.2, 1. ],
       [4.8, 1.6, 0.2, 1. ],
       [4.8, 1.4, 0.1, 1. ],
       [4.3, 1.1, 0.1, 1. ],
       [5.8, 1.2, 0.2, 1. ],
       [5.7, 1.5, 0.4, 1. ],
       [5.4, 1.3, 0.4, 1. ],
       [5.1, 1.4, 0.3, 1. ],
       [5.7, 1.7, 0.3, 1. ],
       [5.1, 1.5, 0.3, 1. ],
       [5.4, 1.7, 0.2, 1. ],
       [5.1, 1.5, 0.4, 1. ],
       [4.6, 1. , 0.2, 1. ],
       [5.1, 1.7, 0.5, 1. ],
       [4.8, 1.9, 0.2, 1. ],
       [5. , 1.6, 0.2, 1. ],
       [5. , 1.6, 0.4, 1. ],
       [5.2, 1.5, 0.2, 1. ],
       [5.2, 1.4, 0.2, 1. ],
       [4.7, 1.6, 0.2, 1. ],
       [4.8, 1.6, 0.2, 1. ],
       [5.4, 1.5, 0.4, 1. ],
       [5.2, 1.5, 0.1, 1. ],
       [5.5, 1.4, 0.2, 1. ],
       [4.9, 1

In [133]:
# on supprime les ligne à l'index 1, 2, 3, 4
np.delete(iris, [1,2,3,4], axis = 0)

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.6, 0.2, 1. ],
       [4.8, 3.1, 1.6, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4

In [135]:
np.delete(notre_tableau,1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [136]:
# diviser un tableau avec numpy (tableau à une dimension)(méthode .split)
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [137]:
import numpy as np 
notre_tableau1, notre_tableau2, notre_tableau3 = np.split(notre_tableau,[2, 6])
print(notre_tableau1, notre_tableau2, notre_tableau3)

[1 2] [3 4 5 6] [ 7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [139]:
# diviser un tableau avec numpy (tableau à 2 dimension)(méthode .vsplit) (vertical split)
tableau = np.array([[2,5,6],[9,10,11],[5,6,7]], dtype = "float")
print("Avant division")
print(tableau)
tableau1, tableau2 = np.vsplit(tableau, [2])
print("Après division")
print(tableau1)
print(tableau2)

Avant division
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  7.]]
Après division
[[ 2.  5.  6.]
 [ 9. 10. 11.]]
[[5. 6. 7.]]


In [140]:
# diviser un tableau avec numpy (tableau à 2 dimension)(méthode .hsplit) (horizontal split)
tableau = np.array([[2,5,6],[9,10,11],[5,6,9]], dtype = "float")
print("Avant division")
print(tableau)
tableau1, tableau2 = np.hsplit(tableau, [2])
print("Après division")
print(tableau1)
print(tableau2)

Avant division
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]
Après division
[[ 2.  5.]
 [ 9. 10.]
 [ 5.  6.]]
[[ 6.]
 [11.]
 [ 9.]]


In [142]:
# Concaténer/combiner des tableaux
# méthode .concatenate()
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = "float")
array2 = np.array([[2,5,6],[9,10,11],[5,6,9]], dtype = "float")
print(array1)
print(array2)
np.concatenate([array1, array2])

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 2.,  5.,  6.],
       [ 9., 10., 11.],
       [ 5.,  6.,  9.]])

In [143]:
array3 = np.array([[4,10,13],[7,14,15]], dtype = "float")
np.concatenate([array1, array2, array3])

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 2.,  5.,  6.],
       [ 9., 10., 11.],
       [ 5.,  6.,  9.],
       [ 4., 10., 13.],
       [ 7., 14., 15.]])

In [144]:
# la fonction vstack()(vertical)
import numpy as np 
array1 = np.array([15,16,47])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = "float")
print(array1)
print("---")
print(array2)
print("---")
print(np.vstack([array1, array2]))

[15 16 47]
---
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
---
[[15. 16. 47.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [145]:
array1 = np.array([[15],[16],[47]])
print("---")
print(array1)
print("---")
print(array2)
print("---")
print(np.hstack([array1, array2]))

---
[[15]
 [16]
 [47]]
---
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
---
[[15.  1.  2.  3.]
 [16.  4.  5.  6.]
 [47.  7.  8.  9.]]


In [146]:
array2*array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

In [147]:
np.mat(array2)*np.mat(array2)

matrix([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

In [159]:
iris_mean = np.mean(iris[:,:4], axis=1)
iris_mean
print(np.insert(iris, 5,iris_mean, axis=1))

[[5.1   3.5   1.4   0.2   1.    2.55 ]
 [4.9   3.    1.4   0.2   1.    2.375]
 [4.7   3.2   1.3   0.2   1.    2.35 ]
 [4.6   3.1   1.5   0.2   1.    2.35 ]
 [5.    3.6   1.4   0.2   1.    2.55 ]
 [5.4   3.9   1.7   0.4   1.    2.85 ]
 [4.6   3.4   1.4   0.3   1.    2.425]
 [5.    3.4   1.5   0.2   1.    2.525]
 [4.4   2.9   1.4   0.2   1.    2.225]
 [4.9   3.1   1.5   0.1   1.    2.4  ]
 [5.4   3.7   1.5   0.2   1.    2.7  ]
 [4.8   3.4   1.6   0.2   1.    2.5  ]
 [4.8   3.    1.4   0.1   1.    2.325]
 [4.3   3.    1.1   0.1   1.    2.125]
 [5.8   4.    1.2   0.2   1.    2.8  ]
 [5.7   4.4   1.5   0.4   1.    3.   ]
 [5.4   3.9   1.3   0.4   1.    2.75 ]
 [5.1   3.5   1.4   0.3   1.    2.575]
 [5.7   3.8   1.7   0.3   1.    2.875]
 [5.1   3.8   1.5   0.3   1.    2.675]
 [5.4   3.4   1.7   0.2   1.    2.675]
 [5.1   3.7   1.5   0.4   1.    2.675]
 [4.6   3.6   1.    0.2   1.    2.35 ]
 [5.1   3.3   1.7   0.5   1.    2.65 ]
 [4.8   3.4   1.9   0.2   1.    2.575]
 [5.    3.    1.6   0.2  

In [175]:
iris_mean = np.mean(iris, axis=0)
print(np.insert(iris, iris.shape[0], iris_mean, axis=0))

[[5.1        3.5        1.4        0.2        1.        ]
 [4.9        3.         1.4        0.2        1.        ]
 [4.7        3.2        1.3        0.2        1.        ]
 [4.6        3.1        1.5        0.2        1.        ]
 [5.         3.6        1.4        0.2        1.        ]
 [5.4        3.9        1.7        0.4        1.        ]
 [4.6        3.4        1.4        0.3        1.        ]
 [5.         3.4        1.5        0.2        1.        ]
 [4.4        2.9        1.4        0.2        1.        ]
 [4.9        3.1        1.5        0.1        1.        ]
 [5.4        3.7        1.5        0.2        1.        ]
 [4.8        3.4        1.6        0.2        1.        ]
 [4.8        3.         1.4        0.1        1.        ]
 [4.3        3.         1.1        0.1        1.        ]
 [5.8        4.         1.2        0.2        1.        ]
 [5.7        4.4        1.5        0.4        1.        ]
 [5.4        3.9        1.3        0.4        1.        ]
 [5.1        3